# This is a basic workflow to help you get started with Actions

name: CI-Coverage

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
  runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
    - name: Install gcov 
      run: sudo apt -y install gcovr
    - name: make coverage
      run: make -C 3_Implementation/coverageCheck
    - name: GCov only
      run:  gcovr -r .
